### ISSUE TITLE
Any updates?

### ISSUE THREAD

**Issue by sysadminpower2019** [OpenRTX/sa8x8-fw#18]
This looks like a great project

**Comment by edgetriggered** [comment]
This project is already feature complete for my needs so I haven't spent time working on it lately. There was some discussion about adding support for hardware PTT toggle and I have an untested proof of concept in my personal repository. OpenRTX support for LilyGo T-TWR Plus relies on this firmware and currently supports FM mode with plans for M17. I also recently adapted rl78flash so that any applications written for Zephyr RTOS can easily program a connected SA868S module.
